version: '3.8'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - data_volume:/data/:rw
      - adminer_volume:/var/www/adminer/
      - ./bonus/portfolio/src/:/var/www/html/
    networks:
      - hchakoub_network
    depends_on:
      - wordpress
      - adminer
      - grafana
      - portfolio
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - data_volume:/data/:rw
    depends_on:
      - mariadb
      - redis
    networks:
        - hchakoub_network
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "WP_TITLE=${WP_TITLE}"
      - "WP_ADMIN=${WP_ADMIN}"
      - "WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}"
      - "WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}"
      - "WP_URL=${WP_URL}"
      - "WP_USER=${WP_USER}"
      - "WP_USER_EMAIL=${WP_USER_EMAIL}"
      - "WP_USER_PASSWORD=${WP_USER_PASSWORD}"
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql/:rw
    networks:
      - hchakoub_network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    restart: always
  redis:
    container_name: redis
    build: ./bonus/redis/
    networks:
      - hchakoub_network
  ftp:
    container_name: ftp
    build: ./bonus/ftp/
    ports:
      - "21:21"
    volumes:
      - data_volume:/home/${FTP_USER}:rw
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_ROOT_PASSWORD=${FTP_ROOT_PASSWORD}
    restart: always
  adminer:
    container_name: adminer
    build: ./bonus/adminer/
    networks:
      - hchakoub_network
    volumes:
      - adminer_volume:/var/www/adminer/
    restart: always
  # portfolio [ begin ]
  portfolio:
    container_name: portfolio
    build: ./bonus/portfolio/
    networks:
      - hchakoub_network
    volumes:
      - ./bonus/portfolio/src/:/var/www/html/
    restart: always
  # portfolio [ end ]
  # monitoring services [ BEGIN ]
  grafana:
    container_name: grafana
    extends:
      file: ./bonus/monitoring/docker-compose.yml
      service: grafana
  prometheus:
    container_name: prometheus
    extends:
      file: ./bonus/monitoring/docker-compose.yml
      service: prometheus
  cadvisor:
    container_name: cadvisor
    extends:
      file: ./bonus/monitoring/docker-compose.yml
      service: cadvisor
  node-exporter:
    container_name: node-exporter
    extends:
      file: ./bonus/monitoring/docker-compose.yml
      service: node-exporter
  # monitoring services [ END ]

volumes:
  data_volume:
    driver: local
    driver_opts:
      type: 'bind'
      o: 'bind'
      device: /home/${USER}/data/wordpress/
  db_volume:
    driver: local
    driver_opts:
      type: 'bind'
      o: 'bind'
      device: /home/${USER}/data/mariadb/
  adminer_volume:
  grafana_data:
networks:
  hchakoub_network:
    driver: bridge