version: '3.8'
services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data_volume:/data/:rw
    networks:
      - hchakoub_network
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress/
    volumes:
      - data_volume:/data/:rw
    depends_on:
      - mysql
      - redis
    networks:
        - hchakoub_network
    environment:
      - "MYSQL_HOST=${MYSQL_HOST}"
  mysql:
    build: ./requirements/mysql/
    volumes:
      - db_volume:/var/lib/mysql/data:rw
    networks:
      - hchakoub_network
  redis:
    build: ./bonus/redis/
    networks:
      - hchakoub_network
  ftp:
    build: ./bonus/ftp/
    volumes:
      - data_volume:/data/:rw
volumes:
  data_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hchakoub/data/web'
  db_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hchakoub/data/mysql'
networks:
  hchakoub_network:
    driver: bridge