version: '3.8'
services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - data_volume:/data/:rw
    networks:
      - hchakoub_network
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress/
    volumes:
      - data_volume:/data/:rw
    depends_on:
      - mysql
      - redis
    networks:
        - hchakoub_network
    environment:
      - "DB_HOST=${DB_HOST}"
      - "WP_TITLE=${WP_TITLE}"
      - "WP_ADMIN=${WP_ADMIN}"
      - "WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}"
      - "WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}"
      - "WP_URL=${WP_URL}"
      - "WP_USER=${WP_USER}"
      - "WP_USER_EMAIL=${WP_USER_EMAIL}"
      - "WP_USER_PASSWORD=${WP_USER_PASSWORD}"

  mysql:
    build:
      context: ./requirements/mysql/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql/:rw
    networks:
      - hchakoub_network
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  redis:
    build: ./bonus/redis/
    networks:
      - hchakoub_network
  ftp:
    build: ./bonus/ftp/
    ports:
      - "21:21"
    volumes:
      - data_volume:/home/${FTP_USER}:rw
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_ROOT_PASSWORD=${FTP_ROOT_PASSWORD}
    restart: always
volumes:
  data_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hchakoub/data/wordpress/'
  db_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hchakoub/data/mariadb/'
networks:
  hchakoub_network:
    driver: bridge