version: '3.8'
services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - data_volume:/data/:rw
      - adminer_volume:/var/www/adminer/
      - ./bonus/portfolio/src/:/var/www/html/
    networks:
      - hchakoub_network
    depends_on:
      - wordpress
      - adminer
      - grafana
  wordpress:
    build: ./requirements/wordpress/
    volumes:
      - data_volume:/data/:rw
    depends_on:
      - mysql
      - redis
    networks:
        - hchakoub_network
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "WP_TITLE=${WP_TITLE}"
      - "WP_ADMIN=${WP_ADMIN}"
      - "WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}"
      - "WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}"
      - "WP_URL=${WP_URL}"
      - "WP_USER=${WP_USER}"
      - "WP_USER_EMAIL=${WP_USER_EMAIL}"
      - "WP_USER_PASSWORD=${WP_USER_PASSWORD}"

  mysql:
    build:
      context: ./requirements/mysql/
    volumes:
      - db_volume:/var/lib/mysql/:rw
    networks:
      - hchakoub_network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    restart: always
  redis:
    build: ./bonus/redis/
    networks:
      - hchakoub_network
  ftp:
    build: ./bonus/ftp/
    ports:
      - "21:21"
    volumes:
      - data_volume:/home/${FTP_USER}:rw
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_ROOT_PASSWORD=${FTP_ROOT_PASSWORD}
    restart: always
  adminer:
    build: ./bonus/adminer/
    networks:
      - hchakoub_network
    volumes:
      - adminer_volume:/var/www/adminer/
# monitoring services [ BEGIN ]
  grafana:
    extends:
      file: ./bonus/monitoring/docker-compose.yml
      service: grafana
  prometheus:
    extends:
      file: ./bonus/monitoring/docker-compose.yml
      service: prometheus
  cadvisor:
    extends:
      file: ./bonus/monitoring/docker-compose.yml
      service: cadvisor
  node-exporter:
    extends:
      file: ./bonus/monitoring/docker-compose.yml
      service: node-exporter
# monitoring services [ END ]

volumes:
  data_volume:
    driver: local
    driver_opts:
      type: 'bind'
      o: 'bind'
      device: /home/${USER}/data/wordpress/
  db_volume:
    driver: local
    driver_opts:
      type: 'bind'
      o: 'bind'
      device: /home/${USER}/data/mariadb/
  adminer_volume:
networks:
  hchakoub_network:
    driver: bridge