version: '3.8'
services:
  node-exporter: 
    build: ./node-exporter/
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    networks:
      - hchakoub_network
    ports:
      - "9100:9100"
  cadvisor:
    build: ./cadvisor/
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - hchakoub_network
  prometheus:
    build: ./prometheus/
    networks:
      - hchakoub_network
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
      - node-exporter
  grafana:
    build: ./grafana/
    networks:
      - hchakoub_network
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
# networks:
#   srcs_hchakoub_network:
#     external: true
