version: '3.8'
services:
  node-exporter: 
    build: ./node-exporter/
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    networks:
      - hchakoub_network
    restart: always
  cadvisor:
    build: ./cadvisor/
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - hchakoub_network
    restart: always
  prometheus:
    build: ./prometheus/
    networks:
      - hchakoub_network
    depends_on:
      - cadvisor
      - node-exporter
    restart: always
  grafana:
    build: ./grafana/
    networks:
      - hchakoub_network
    volumes:
      - grafana_data:/usr/share/grafana/data
    restart: always
    depends_on:
      - prometheus

