version: '3.8'
services:
  node-exporter: 
    build: ./node-exporter/
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      # - '-collector.filesystem.mount-points-    exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    networks:
      - night_watch
    ports:
      - "9100:9100"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - night_watch
  prometheus:
    build: ./prometheus/
    networks:
      - night_watch
    ports:
      - "9090:9090"
  grafana:
    build: ./grafana/
    networks:
      - night_watch
    ports:
      - "3000:3000"
networks:
  night_watch:
